### ISSUE TITLE
spawn makensis ENOENT on "npm run release" in windows

### ISSUE THREAD

**Issue by blueforest** [szwacz/nw-boilerplate#22]
I install NSIS successfully,and add folder to PATH in Enviroment Variables("C:\Program Files (x86)\NSIS"),when i execute "npm run release" an error occured.
`Error: spawn makensis ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

**Comment by suprsidr** [comment]
After you alter PATH, you need to close your command console and re-open.
